/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Date = IDL.Int;
export const Category = IDL.Variant({
  'salary' : IDL.Null,
  'miscellaneous' : IDL.Null,
  'marketing' : IDL.Null,
  'development' : IDL.Null,
  'officeExpense' : IDL.Null,
  'vendorCost' : IDL.Null,
});
export const Amount = IDL.Float64;
export const PaymentMode = IDL.Variant({
  'upi' : IDL.Null,
  'bank' : IDL.Null,
  'cash' : IDL.Null,
});
export const ExpenseId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExpensePartial = IDL.Record({
  'date' : IDL.Opt(Date),
  'description' : IDL.Opt(IDL.Text),
  'paymentMode' : IDL.Opt(PaymentMode),
  'category' : IDL.Opt(Category),
  'amount' : IDL.Opt(Amount),
  'paidAmount' : IDL.Opt(Amount),
  'receiptUrl' : IDL.Opt(IDL.Text),
});
export const Time = IDL.Int;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'date' : Date,
  'createdAt' : Time,
  'description' : IDL.Text,
  'paymentMode' : PaymentMode,
  'category' : Category,
  'amount' : Amount,
  'paidAmount' : Amount,
  'receiptUrl' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CategorySummary = IDL.Record({
  'totalAmount' : Amount,
  'category' : Category,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpense' : IDL.Func(
      [Date, Category, Amount, IDL.Text, PaymentMode, Amount, IDL.Opt(IDL.Text)],
      [ExpenseId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'editExpense' : IDL.Func([ExpenseId, ExpensePartial], [Expense], []),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategorySummary' : IDL.Func([], [IDL.Vec(CategorySummary)], ['query']),
  'getExpense' : IDL.Func([ExpenseId], [Expense], ['query']),
  'getExpensesByCategory' : IDL.Func([Category], [IDL.Vec(Expense)], ['query']),
  'getExpensesByDateRange' : IDL.Func(
      [Date, Date],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getExpensesByPaymentMode' : IDL.Func(
      [PaymentMode],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getTotalAmount' : IDL.Func([], [Amount], ['query']),
  'getTotalPaidAmount' : IDL.Func([], [Amount], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Date = IDL.Int;
  const Category = IDL.Variant({
    'salary' : IDL.Null,
    'miscellaneous' : IDL.Null,
    'marketing' : IDL.Null,
    'development' : IDL.Null,
    'officeExpense' : IDL.Null,
    'vendorCost' : IDL.Null,
  });
  const Amount = IDL.Float64;
  const PaymentMode = IDL.Variant({
    'upi' : IDL.Null,
    'bank' : IDL.Null,
    'cash' : IDL.Null,
  });
  const ExpenseId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExpensePartial = IDL.Record({
    'date' : IDL.Opt(Date),
    'description' : IDL.Opt(IDL.Text),
    'paymentMode' : IDL.Opt(PaymentMode),
    'category' : IDL.Opt(Category),
    'amount' : IDL.Opt(Amount),
    'paidAmount' : IDL.Opt(Amount),
    'receiptUrl' : IDL.Opt(IDL.Text),
  });
  const Time = IDL.Int;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'date' : Date,
    'createdAt' : Time,
    'description' : IDL.Text,
    'paymentMode' : PaymentMode,
    'category' : Category,
    'amount' : Amount,
    'paidAmount' : Amount,
    'receiptUrl' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CategorySummary = IDL.Record({
    'totalAmount' : Amount,
    'category' : Category,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpense' : IDL.Func(
        [Date, Category, Amount, IDL.Text, PaymentMode, Amount, IDL.Opt(IDL.Text)],
        [ExpenseId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'editExpense' : IDL.Func([ExpenseId, ExpensePartial], [Expense], []),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategorySummary' : IDL.Func([], [IDL.Vec(CategorySummary)], ['query']),
    'getExpense' : IDL.Func([ExpenseId], [Expense], ['query']),
    'getExpensesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByDateRange' : IDL.Func(
        [Date, Date],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByPaymentMode' : IDL.Func(
        [PaymentMode],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getTotalAmount' : IDL.Func([], [Amount], ['query']),
    'getTotalPaidAmount' : IDL.Func([], [Amount], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };